# Generated by Django 4.1.3 on 2023-05-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_1', models.BooleanField(default=False)),
                ('front_2', models.BooleanField(default=False)),
                ('front_3', models.BooleanField(default=False)),
                ('front_4', models.BooleanField(default=False)),
                ('front_5', models.BooleanField(default=False)),
                ('back_6', models.BooleanField(default=False)),
                ('back_7', models.BooleanField(default=False)),
                ('back_8', models.BooleanField(default=False)),
                ('back_9', models.BooleanField(default=False)),
                ('back_10', models.BooleanField(default=False)),
                ('passenger_11', models.BooleanField(default=False)),
                ('passenger_12', models.BooleanField(default=False)),
                ('passenger_13', models.BooleanField(default=False)),
                ('passenger_14', models.BooleanField(default=False)),
                ('passenger_15', models.BooleanField(default=False)),
                ('passenger_16', models.BooleanField(default=False)),
                ('passenger_17', models.BooleanField(default=False)),
                ('passenger_18', models.BooleanField(default=False)),
                ('passenger_19', models.BooleanField(default=False)),
                ('top_20', models.BooleanField(default=False)),
                ('top_21', models.BooleanField(default=False)),
                ('top_22', models.BooleanField(default=False)),
                ('top_23', models.BooleanField(default=False)),
                ('driver_24', models.BooleanField(default=False)),
                ('driver_25', models.BooleanField(default=False)),
                ('driver_26', models.BooleanField(default=False)),
                ('driver_27', models.BooleanField(default=False)),
                ('driver_28', models.BooleanField(default=False)),
                ('driver_29', models.BooleanField(default=False)),
                ('driver_30', models.BooleanField(default=False)),
                ('driver_31', models.BooleanField(default=False)),
                ('driver_32', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('karpet', models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True)),
                ('kursi', models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True)),
                ('headliner', models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True)),
                ('door_panels', models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
    ]
