# Generated by Django 4.1.3 on 2023-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalinspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_30',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_31',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_32',
            field=models.BooleanField(default=''),
        ),
    ]
