# Generated by Django 4.1.3 on 2023-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalinspection', '0002_alter_finalinspection_driver_30_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_31',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='driver_32',
            field=models.BooleanField(default=False),
        ),
    ]
