# Generated by Django 3.2.18 on 2023-05-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('nomor_pkb', models.IntegerField()),
                ('nomor_polisi', models.IntegerField()),
                ('merk_type', models.CharField(max_length=70)),
                ('pelanggan', models.CharField(max_length=70)),
                ('keterangan_lain_lain', models.CharField(max_length=70)),
                ('total_harga_service', models.IntegerField()),
                ('total_harga_sparepart', models.IntegerField()),
                ('total_harga_lainlain', models.IntegerField(null=True)),
                ('total_harga_gabungan', models.IntegerField()),
                ('petugas_gudang', models.BooleanField(default=False)),
                ('petugas_bengkel', models.BooleanField(default=False)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
    ]
