# Generated by Django 4.1.3 on 2023-05-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_services'),
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_barang', models.IntegerField()),
                ('total_harga_sparepart', models.IntegerField()),
                ('petugas_gudang', models.BooleanField(default=False)),
                ('petugas_bengkel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotaGabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_gabungan', models.IntegerField()),
                ('tanggal', models.DateField()),
                ('keterangan_lain_lain', models.CharField(max_length=70)),
                ('total_harga_service', models.IntegerField()),
                ('total_harga_sparepart', models.IntegerField()),
                ('total_harga_lainlain', models.IntegerField(null=True)),
                ('total_harga_gabungan', models.IntegerField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('nota_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota.notabarang')),
            ],
        ),
        migrations.CreateModel(
            name='NotaJasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_jasa', models.IntegerField()),
                ('total_harga_service', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.AddField(
            model_name='notagabungan',
            name='nota_jasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nota.notajasa'),
        ),
    ]
