# Generated by Django 4.1.3 on 2023-05-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_notabarang_notagabungan_notajasa_delete_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notagabungan',
            name='keterangan_lain_lain',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
