# Generated by Django 3.2.8 on 2023-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=30)),
                ('telepon_pelanggan', models.BigIntegerField()),
                ('alamat_pelanggan', models.TextField()),
                ('jenis_mobil', models.CharField(max_length=30)),
                ('nama_mobil', models.CharField(max_length=30)),
                ('nomor_pkb', models.IntegerField()),
                ('nomor_polisi', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
