# Generated by Django 3.2.8 on 2023-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='nomor_polisi',
            field=models.CharField(max_length=10),
        ),
    ]
