# Generated by Django 3.2.7 on 2023-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_alter_pelanggan_nomor_polisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='telepon_pelanggan',
            field=models.CharField(max_length=15),
        ),
    ]
