# Generated by Django 4.1.3 on 2023-03-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Akuntan', 'Akuntan'), ('Inventori', 'Inventori'), ('Service Advisor', 'Service Advisor'), ('Teknisi', 'Teknisi')], default='', max_length=15),
        ),
    ]
