# Generated by Django 4.1.3 on 2023-03-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_alter_karyawan_jabatan'),
        ('karyawan', '0002_auto_20230319_2146'),
    ]

    operations = [
    ]
