# Generated by Django 3.2.18 on 2023-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.CharField(max_length=10)),
                ('estimasi_pengerjaan', models.CharField(max_length=10)),
            ],
        ),
    ]
