# Generated by Django 4.1.3 on 2023-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sparepart', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kebutuhan_spare_part',
            field=models.ManyToManyField(to='sparepart.sparepart'),
        ),
    ]
