# Generated by Django 3.2.18 on 2023-04-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0003_auto_20230421_1743'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kebutuhan_spare_part',
            field=models.ManyToManyField(to='sparepart.SparePart'),
        ),
        migrations.AddField(
            model_name='service',
            name='satuan_waktu',
            field=models.CharField(choices=[('Menit', 'Menit'), ('Jam', 'Jam'), ('Hari', 'Hari'), ('Minggu', 'Minggu'), ('Bulan', 'Bulan')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='nama',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
