# Generated by Django 3.2.18 on 2023-03-18 19:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_kebutuhan_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kuantitas_spare_part',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='kebutuhan_spare_part',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Baut'), (2, 'Oli'), (3, 'Besi'), (4, 'Bamper'), (5, 'Ban')], default='', max_length=9),
        ),
    ]
