# Generated by Django 3.2.7 on 2023-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20230318_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
