# Generated by Django 4.1.3 on 2023-03-20 16:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
                ('estimasi_pengerjaan', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='kebutuhan_spare_part',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Baut'), (2, 'Oli'), (3, 'Besi'), (4, 'Bamper'), (5, 'Ban')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('variasi', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
                ('kuantitas', models.IntegerField()),
                ('trial_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.trialservice')),
            ],
        ),
    ]
