# Generated by Django 4.1.3 on 2023-04-27 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230413_2107'),
        ('services', '0002_auto_20230425_1834'),
    ]

    operations = [
    ]
