# Generated by Django 4.1.3 on 2023-04-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_harga'),
        ('services', '0006_merge_20230427_1258'),
    ]

    operations = [
    ]
