# Generated by Django 4.1.3 on 2023-05-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
        ('pelanggan', '0003_alter_pelanggan_telepon_pelanggan'),
        ('karyawan', '0001_initial'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelanggan.pelanggan'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='teknisi',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.karyawan'),
        ),
    ]
