# Generated by Django 3.2.18 on 2023-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', through='appointment.AppointmentService', to='services.Service'),
        ),
    ]
