# Generated by Django 4.1.3 on 2023-04-16 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0004_alter_karyawan_jabatan_and_more'),
        ('appointment', '0002_appointment_status_alter_appointment_teknisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='teknisi',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='karyawan.karyawan'),
        ),
    ]
