# Generated by Django 4.1.3 on 2023-04-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230413_2107'),
        ('appointment', '0005_remove_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
