# Generated by Django 4.1.3 on 2023-04-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentService',
        ),
    ]
