# Generated by Django 4.1.3 on 2023-04-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='services',
        ),
    ]
