# Generated by Django 4.1.3 on 2023-05-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kendala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('jumlah_estimasi_pengerjaan', models.IntegerField()),
                ('satuan_waktu', models.CharField(choices=[('Menit', 'Menit'), ('Jam', 'Jam'), ('Hari', 'Hari'), ('Minggu', 'Minggu'), ('Bulan', 'Bulan')], default='', max_length=30)),
                ('appointment_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentservice')),
            ],
        ),
    ]
