# Generated by Django 4.1.3 on 2023-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendala',
            name='status',
            field=models.CharField(choices=[('0', 'Unsolved'), ('1', 'Solved')], default='0', max_length=30),
        ),
    ]
