# Generated by Django 4.1.3 on 2023-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kendala', '0003_alter_kendala_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendala',
            name='status',
            field=models.CharField(choices=[('Unsolved', 'Unsolved'), ('Solved', 'Solved')], default='Unsolved', max_length=30),
        ),
    ]
