# Generated by Django 4.1.3 on 2023-04-17 01:16

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_rangka', models.CharField(max_length=20)),
                ('model_tipe', models.CharField(max_length=255)),
                ('nomor_mesin', models.CharField(max_length=20)),
                ('tahun_kendaraan', models.IntegerField(default=None)),
                ('warna_kendaraan', models.CharField(max_length=50)),
                ('sisa_bensin', models.IntegerField(default=None)),
                ('service_book', models.BooleanField(default=True)),
                ('spare_wheel', models.BooleanField(default=True)),
                ('jack', models.BooleanField(default=True)),
                ('tools', models.BooleanField(default=True)),
                ('radio_tape', models.BooleanField(default=True)),
                ('front_1', models.BooleanField(default=False)),
                ('front_2', models.BooleanField(default=False)),
                ('front_3', models.BooleanField(default=False)),
                ('front_4', models.BooleanField(default=False)),
                ('front_5', models.BooleanField(default=False)),
                ('back_6', models.BooleanField(default=False)),
                ('back_7', models.BooleanField(default=False)),
                ('back_8', models.BooleanField(default=False)),
                ('back_9', models.BooleanField(default=False)),
                ('back_10', models.BooleanField(default=False)),
                ('passenger_11', models.BooleanField(default=False)),
                ('passenger_12', models.BooleanField(default=False)),
                ('passenger_13', models.BooleanField(default=False)),
                ('passenger_14', models.BooleanField(default=False)),
                ('passenger_15', models.BooleanField(default=False)),
                ('passenger_16', models.BooleanField(default=False)),
                ('passenger_17', models.BooleanField(default=False)),
                ('passenger_18', models.BooleanField(default=False)),
                ('passenger_19', models.BooleanField(default=False)),
                ('top_20', models.BooleanField(default=False)),
                ('top_21', models.BooleanField(default=False)),
                ('top_22', models.BooleanField(default=False)),
                ('top_23', models.BooleanField(default=False)),
                ('driver_24', models.BooleanField(default=False)),
                ('driver_25', models.BooleanField(default=False)),
                ('driver_26', models.BooleanField(default=False)),
                ('driver_27', models.BooleanField(default=False)),
                ('driver_28', models.BooleanField(default=False)),
                ('driver_29', models.BooleanField(default=False)),
                ('driver_30', models.BooleanField(default=False)),
                ('driver_31', models.BooleanField(default=False)),
                ('driver_32', models.BooleanField(default=False)),
                ('catatan', models.TextField()),
                ('karpet', multiselectfield.db.fields.MultiSelectField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50)),
                ('kursi', multiselectfield.db.fields.MultiSelectField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50)),
                ('headliner', multiselectfield.db.fields.MultiSelectField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50)),
                ('door_panels', multiselectfield.db.fields.MultiSelectField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50)),
            ],
        ),
    ]
