# Generated by Django 4.1.3 on 2023-04-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialinspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinspection',
            name='door_panels',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='headliner',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='karpet',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='kursi',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default=None, max_length=50),
        ),
    ]
