# Generated by Django 4.1.3 on 2023-04-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialinspection', '0003_alter_initialinspection_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinspection',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='door_panels',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='headliner',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='karpet',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='kursi',
            field=models.CharField(choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50),
        ),
    ]
