# Generated by Django 4.1.3 on 2023-04-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialinspection', '0004_alter_initialinspection_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinspection',
            name='door_panels',
            field=models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='headliner',
            field=models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='karpet',
            field=models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='initialinspection',
            name='kursi',
            field=models.CharField(blank=True, choices=[('W', 'Worn'), ('B', 'Burns'), ('R', 'Ripped'), ('S', 'Stain'), ('C', 'Cracked')], default='', max_length=50, null=True),
        ),
    ]
