# Generated by Django 4.1.3 on 2023-04-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_teknisi'),
        ('initialinspection', '0005_alter_initialinspection_door_panels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialinspection',
            name='appointment',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
            preserve_default=False,
        ),
    ]
