# Generated by Django 4.1.3 on 2023-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('variasi', models.CharField(max_length=70)),
                ('harga', models.BigIntegerField(default='')),
                ('stok', models.IntegerField(default='')),
                ('services', models.ManyToManyField(to='services.service')),
            ],
        ),
    ]
