# Generated by Django 3.2.18 on 2023-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('variasi', models.IntegerField()),
                ('harga', models.IntegerField(default='')),
                ('stok', models.IntegerField(default='')),
            ],
        ),
    ]
