# Generated by Django 3.2.18 on 2023-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '__first__'),
        ('sparepart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='variasi',
            field=models.CharField(max_length=30),
        ),
    ]
