# Generated by Django 3.2.18 on 2023-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparepart', '0002_auto_20230413_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='harga',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='nama',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='variasi',
            field=models.CharField(max_length=70),
        ),
    ]
